- name: Deploy Services with Docker
  hosts: all
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/ubuntu/key.pem
    port_map:
      mysql: "3306:3306"
      nginx: "80:80"
    days_map:
      Sunday: 0
      Monday: 1
      Tuesday: 2
      Wednesday: 3
      Thursday: 4
      Friday: 5
      Saturday: 6

  tasks:

    - name: Stop conflicting system services (from previous exercise)
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      ignore_errors: yes 
      loop:
        - mysql
        - nginx
        - apache2

 
    - name: Install Docker and Python dependencies
      apt:
        pkg:
          - docker.io
          - python3-docker
        state: present
        update_cache: yes

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Set Hostname
      hostname:
        name: "{{ tags.Name }}"
      when: tags.Name is defined

    - name: Run Service Container
      community.docker.docker_container:
        name: "{{ tags.Service }}"
      
        image: "{{ tags.Service }}:{{ (tags.Version | default('') | length > 0) | ternary(tags.Version, 'latest') }}"
        state: started
        restart_policy: always
        ports:
          - "{{ port_map[tags.Service] }}"
        env:
          MYSQL_ROOT_PASSWORD: "Password123!"
      when:
        - tags.Service is defined
        - tags.Service in port_map

    - name: Setup Restart Cron Job
      cron:
        name: "Restart Server based on Tag"
        minute: "0"
        hour: "{{ (tags.Restart | regex_search('(\\d+):(\\d+)', '\\1') | first) | default('0') }}"
        weekday: "{{ days_map[tags.Restart.split(' ')[0]] }}"
        job: "/sbin/shutdown -r now"
      when: tags.Restart is defined


